### ISSUE TITLE
[Bug] v0.1.5 globalize_accessors(locales: FROZEN_ARRAY)

### ISSUE THREAD

**Issue by Epigene** [globalize/globalize-accessors#33]
Hi! Thanks for the useful gem!

I encountered an error when passing a frozen locales hash to `globalize_accessors` method.  
It seems to me to be a bug, since config like this should definitely use frozen constants and globalize-accessors should support this.

```rb
APP_LOCALES = [:en, :de].freeze
globalize_accessors(locales: APP_LOCALES)
```

```
RuntimeError:
        can't modify frozen Array

  # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/globalize-validations-0.0.4/lib/globalize-validations/concern.rb:35:in `map!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/globalize-validations-0.0.4/lib/globalize-validations/concern.rb:35:in `globalized_errors_for_locales'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/globalize-validations-0.0.4/lib/globalize-validations/concern.rb:22:in `validates_globalized_attributes'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:424:in `block in make_lambda'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:184:in `call'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:184:in `block in simple'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:185:in `call'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:185:in `block in simple'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `call'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `run_callbacks'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activemodel-4.1.5/lib/active_model/validations.rb:376:in `run_validations!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activemodel-4.1.5/lib/active_model/validations/callbacks.rb:111:in `block in run_validations!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:82:in `run_callbacks'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activemodel-4.1.5/lib/active_model/validations/callbacks.rb:111:in `run_validations!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activemodel-4.1.5/lib/active_model/validations.rb:317:in `valid?'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/validations.rb:70:in `valid?'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/validations.rb:77:in `perform_validations'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/validations.rb:57:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `block in save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `save!'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/notifications.rb:161:in `instrument'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
      # ./spec/models/macro_message_spec.rb:196:in `block (3 levels) in <top (required)>'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `block in load'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
      # /Users/developer/.rvm/gems/ruby-2.1.2@sha/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
      # -e:1:in `<main>'
```

Needless to say, adding freeze-removing `.dup` at the end of the constant sidesteps the problem.

```rb
APP_LOCALES = [:en, :de].freeze
globalize_accessors(locales: APP_LOCALES.dup)
```

**Comment by shioyama** [comment]
Looks like from your trace the error is coming from [globalize-validations](https://github.com/BookingSync/globalize-validations), not globalize-accessors.

**Comment by shioyama** [comment]
And there is [already an issue for it](https://github.com/BookingSync/globalize-validations).
